name: Deployment Request
description: Request a deployment to an environment
title: "DEPLOY <target> to <environment>"
labels:
  - "Deployment Request"
  - "invalid"
body:
  - type: dropdown
    id: environment
    attributes:
      label: Target Deployment Environment
      description: Select the target environment for this deployment.
      options:
        - Staging
        - Production
    validations:
      required: true
  - type: dropdown
    id: target
    attributes:
      label: Target Repository Reference
      description: Select the target repository reference type for this deployment.
      options:
        - Branch
        - Commit
        - Tag
    validations:
      required: true

  - type: input
    id: reference
    attributes:
      label: Reference Value
      description: "Specify the branch, tag, or commit you want to deploy."
      placeholder: "main"
    validations:
      required: true

