#Main file
name: Deployment
run-name: Deploy ${{inputs.referenceValue}} to ${{ inputs.targetEnvironment }} by @${{ github.actor }}
concurrency: Deployments

on:
  workflow_dispatch:
    inputs:
      targetEnvironment:
        description: 'Target Deployment Environment'
        required: true
        default: ''
      targetReference:
        description: 'Target Repository Reference'
        required: true
        default: ''        
      referenceValue:
        description: 'Reference Value'
        required: true
        default: ''        

jobs:
  staging:
    runs-on: ubuntu-latest
    environment: ${{inputs.targetEnvironment}}
    steps:
      - name: deploy
        run: echo "deployed ${{inputs.referenceValue}} to ${{inputs.targetEnvironment}}"
      - name: Checkout code
        uses: actions/checkout@v4 
        with:
          ref: ${{ inputs.referenceValue }}
          fetch-tags: true
      - name: Generate Container Tag
        run: |
            TAGS=()
            TAG_NAME=$(git describe --tags --exact-match 2> /dev/null || echo "")
            if [ -n "$TAG_NAME" ]; then
            TAGS+=("$TAG_NAME")
            fi
            # PACKAGE_VERSION=$(jq -r '.version' ./package.json)
            # if [ -n "$PACKAGE_VERSION" ]; then
            #     TAGS+=("$PACKAGE_VERSION")
            # fi
            COMMIT_HASH=$(git rev-parse --short HEAD)
            TAGS+=("$COMMIT_HASH")
            TAGS_STR=$(IFS=, ; echo "${TAGS[*]}")
            echo "Collected tags: $TAGS_STR"
            echo "TAGS=$TAGS_STR" >> $GITHUB_ENV
