#Main file
name: Deployment
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
concurrency: Production

on:
  push:
    branches:
      - test
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Target deployment environment'
        required: true
        default: 'staging'

jobs:
  staging:
      runs-on: ubuntu-latest
      environment: Staging
      steps:
       - name: deploy
         run: echo "deployed"
