#Main file
name: Deployment
run-name: Deploy ${{inputs.referenceValue}} to ${{ inputs.targetEnvironment }} by @${{ github.actor }}
concurrency: Deployments

on:
  workflow_dispatch:
    inputs:
      targetEnvironment:
        description: 'Target Deployment Environment'
        required: true
        default: 'Staging'
      targetReference:
        description: 'Target Repository Reference'
        required: true
        default: 'Branch'        
      referenceValue:
        description: 'Reference Value'
        required: true
        default: 'main'        

jobs:
  staging:
      runs-on: ubuntu-latest
      environment: ${{inputs.targetEnvironment}}
      steps:
       - name: deploy
         run: echo "deployed ${{inputs.referenceValue}}"
