#Main file
name: Deployment

concurrency: Production

on:
  push:
    branches:
      - test
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Target deployment environment'
        required: true
        default: 'staging'

jobs:
  staging:
    deployment:
      runs-on: ubuntu-latest
      environment: Production
      steps:
       - name: deploy
         run: echo "deployed"
